version: '3'

services:
  pets-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: neelypatel/pets-app
    container_name: pets-app
    env_file: .env
    environment:
      - HELLO=$HELLO
    ports:
      - "3001:3001"
    restart: on-failure
    depends_on:
      - mongo

  mongo:
    image: mongo:bionic
    container_name: pets-app-db
    env_file: .env
    ports:
      - "27017:27017"
    volumes:
      - ~/Volumes/mongo:/data/db