version: '3'

services:
  pets-app:
    build:
      context: .
    image: neelypatel/pets-app
    container_name: pets-app
    ports:
      - "3001:3001"
    networks:
      - pets
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    container_name: pets-app-db
    ports:
      - "27017:27017"
    volumes:
      - ~/Volumes/pets:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    networks:
      - pets

networks:
  pets:
    external: true