apiVersion: apps/v1
kind: Deployment
metadata:
  name: pets-app-deployment
  labels:
    app: pets-app
spec:
  selector:
    matchLabels:
      app: pets-app
  template:
    metadata:
      labels:
        app: pets-app
    spec:
      containers:
      - name: pets-app
        image: pets-app:prod
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3001
